# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  关于: /about

logo: http://prr6elh1d.sabkt.gdipper.com/static/logo.png
# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: true

# 默认音乐
mp3:
  - http://prr6elh1d.sabkt.gdipper.com/static/mp3/abc.mp3
  - http://prr6elh1d.sabkt.gdipper.com/static/mp3/我们不一样.mp3
  - http://prr6elh1d.sabkt.gdipper.com/static/mp3/山丘.mp3
  - http://prr6elh1d.sabkt.gdipper.com/static/mp3/曾经的你.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: http://prr6elh1d.sabkt.gdipper.com/static/images/IMG_3334.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: 'a890b5725d0d223421b3'
    # 应用秘钥
    clientSecret: '56b6eba79c2ba3b6015d20fd458478237d6aa802'
    # issue仓库名
    repo: 'yaooort.github.io'
    # Github名
    owner: 'Yaooort'
    # Github名
    admin: ['Yaooort']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Oort Yaooort

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.ico

# rss文件
rss: atom.xml
